name: alpine-nghttp2-build-push-docker

on:
  push:
    paths:
      - 'alpine-nghttp2/**'
  workflow_dispatch:

env:
  IMAGE_NAME: "erezarbell/nghttp2"

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: alpine-nghttp2/
          file: ./Dockerfile
          load: true
          tags: ${{ env.IMAGE_NAME }}:latest
      -
        name: Inspect Image
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:latest
      -
        name: Test Image
        run: |
          docker run ${{ env.IMAGE_NAME }}:latest h2load --h1 https://example.com | grep '1 succeeded'
      -
        name: Login to DockerHub
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push image
        if: success() && github.ref == 'refs/heads/main'
        run: |
            tag=${GITHUB_REF##*/}-$GITHUB_RUN_NUMBER
            docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:$tag
            docker push ${{ env.IMAGE_NAME }}:$tag
            docker push ${{ env.IMAGE_NAME }}:latest
